### ISSUE TITLE
hollow cylinder

### ISSUE THREAD

**Issue by jjYBdx4IL** [printingin3d/javascad#2]
I'm trying to create a hollow cylinder and export it to .stl:

https://github.com/jjYBdx4IL/javascad/blob/mydev1/src/test/java/eu/printingin3d/javascad/models/HollowCylinderTest.java

However, when importing that into FreeCAD, it tells me that there is no data in the STL file. Any ideas?

**Comment by printingin3d** [comment]
The STL export is still very much experimental - and the result is almost never printable. In this particular case the first problem is that the two cylinders have the same height - this causes problems even to OpenSCAD too. If you make the innerCylinder taller (eg: adding 1 to its height) the result is not empty. But still not correct - so I'll check it.

Until I fix it - if I can - you can use the SCAD export and open it in OpenSCAD. That's much more reliable - the STL export has been included as on experiment only.

ps: thanks for the warning fixing commit

**Comment by printingin3d** [comment]
The fix for this issue has been committed to the Master branch.
