### ISSUE TITLE
maven central

### ISSUE THREAD

**Issue by jjYBdx4IL** [printingin3d/javascad#3]
Hey! Could you please upload this to maven central? Would be much easier and cleaner to use. TY!

**Comment by printingin3d** [comment]
It is on the backlist - I have to confess that I abandoned this a bit, because the PGP signature seems a bit complicated. Actually, the POM is ready for the upload, only the signature is missing - I'll try to do that this week, but I cannot promise it for sure.

**Comment by jjYBdx4IL** [comment]
TY! Just use some other maven central project as reference. There is a maven gpg plugin. But put it into a release profile please so others will still be able to do normal builds. I can do that part for you if you are not too familiar with maven profiles.

http://stackoverflow.com/questions/14825039/suppressing-gpg-signing-for-maven-based-continous-integration-builds-travis-ci

Not sure how/if this works on anything other than Linux, though.

**Comment by printingin3d** [comment]
I was not aware of the maven plugin. Thanks for that - it will make the process much easier. I definitely do it this week with the Maven pluging. And I think I can manage the maven profile too, but if I failed I'll ask for advice from you. Thank you.

**Comment by printingin3d** [comment]
Okay, so I deployed JavaSCAD to the nexus repository here: https://oss.sonatype.org/#nexus-search;quick~javascad , but have no idea what's next...

**Comment by printingin3d** [comment]
It seems it's automagically synchronizing to the Maven repository: http://search.maven.org/#artifactdetails|eu.printingin3d.javascad|javascad|0.9.0.11|jar

Today, I'm going to do a proper release - this was just a test, actually. And then we can close this ticket.

**Comment by jjYBdx4IL** [comment]
very nice. ty!
