### ISSUE TITLE
Hull support

### ISSUE THREAD

**Issue by yshrsmz** [printingin3d/javascad#4]
Hi!

It seems like there is no support for [`hull`](https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Transformations#hull) in this library.
Can you add support for this?
Thanks!

**Comment by printingin3d** [comment]
I cannot promise it will be done soon, but sure I can add it to the library.

**Comment by printingin3d** [comment]
It has been implemented in version 0.9.1.0 - it may need some time to reach the central Maven repository.

**Comment by yshrsmz** [comment]
Thanks a lot!
